# -*- coding: utf-8 -*-
"""Lambda_Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHncIwtMGxtdY439VLNie0lSW6m94c9m
"""

import boto3
from datetime import datetime, timezone, timedelta

ec2 = boto3.client('ec2')

# Replace with your volume ID
VOLUME_ID = 'vol-03858640d9e6f80f8'

def lambda_handler(event, context):

    created_snapshot_ids = []
    deleted_snapshot_ids = []

    # Create Snapshot
    snapshot = ec2.create_snapshot(
        VolumeId=VOLUME_ID,
        Description=f"Automated Backup - {datetime.now()}"
    )

    snapshot_id = snapshot['SnapshotId']

    created_snapshot_ids.append(snapshot_id)

    print(f"Created Snapshot: {snapshot_id}")

    # Retention Period
    cutoff_date = datetime.now(
        timezone.utc
    ) - timedelta(days=30)

    # Find Snapshots Owned By Current Account
    snapshots = ec2.describe_snapshots(
        OwnerIds=['self']
    )

    for snap in snapshots['Snapshots']:

        start_time = snap['StartTime']

        if start_time < cutoff_date:

            snapshot_id = snap['SnapshotId']

            try:
                ec2.delete_snapshot(
                    SnapshotId=snapshot_id
                )

                deleted_snapshot_ids.append(
                    snapshot_id
                )

                print(
                    f"Deleted Snapshot: {snapshot_id}"
                )

            except Exception as e:

                print(
                    f"Failed to delete {snapshot_id}: {e}"
                )

    return {
        'statusCode': 200,
        'created_snapshots': created_snapshot_ids,
        'deleted_snapshots': deleted_snapshot_ids
    }