# -*- coding: utf-8 -*-
"""Lambda_Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHncIwtMGxtdY439VLNie0lSW6m94c9m
"""

import boto3
from botocore.exceptions import ClientError

s3 = boto3.client('s3')

def lambda_handler(event, context):

    unencrypted_buckets = []

    buckets = s3.list_buckets()

    for bucket in buckets['Buckets']:

        bucket_name = bucket['Name']

        try:
            s3.get_bucket_encryption(
                Bucket=bucket_name
            )

            print(
                f"{bucket_name} : Encryption Enabled"
            )

        except ClientError as e:

            error_code = e.response['Error']['Code']

            if error_code == 'ServerSideEncryptionConfigurationNotFoundError':

                unencrypted_buckets.append(
                    bucket_name
                )

                print(
                    f"UNENCRYPTED BUCKET: {bucket_name}"
                )

    print(
        f"Total Unencrypted Buckets: {len(unencrypted_buckets)}"
    )

    return {
        'statusCode': 200,
        'unencrypted_buckets': unencrypted_buckets
    }