# -*- coding: utf-8 -*-
"""Lambda_Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grc73lcjd9_Dennh6ijjAazQfB0Xo5G9
"""

import boto3
from datetime import datetime

ec2 = boto3.client('ec2')

def lambda_handler(event, context):

    instance_id = event['detail']['instance-id']

    current_date = datetime.utcnow().strftime(
        '%Y-%m-%d'
    )

    ec2.create_tags(
        Resources=[instance_id],
        Tags=[
            {
                'Key': 'LaunchDate',
                'Value': current_date
            },
            {
                'Key': 'Environment',
                'Value': 'Development'
            }
        ]
    )

    print(
        f"Tagged instance {instance_id}"
    )

    return {
        'statusCode': 200,
        'instance_id': instance_id
    }