# -*- coding: utf-8 -*-
"""Lambda_Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grc73lcjd9_Dennh6ijjAazQfB0Xo5G9
"""

import boto3
from datetime import datetime, timezone, timedelta

s3 = boto3.client('s3')

BUCKET_NAME = 'glacier-archive-demo-suhail'

RETENTION_DAYS = 180

def lambda_handler(event, context):

    cutoff_date = (
        datetime.now(timezone.utc)
        - timedelta(days=RETENTION_DAYS)
    )

    archived_files = []

    response = s3.list_objects_v2(
        Bucket=BUCKET_NAME
    )

    if 'Contents' not in response:

        print("Bucket is empty")

        return {
            'statusCode': 200
        }

    for obj in response['Contents']:

        object_key = obj['Key']

        last_modified = obj['LastModified']

        if last_modified < cutoff_date:

            s3.copy_object(
                Bucket=BUCKET_NAME,
                Key=object_key,
                CopySource={
                    'Bucket': BUCKET_NAME,
                    'Key': object_key
                },
                StorageClass='GLACIER',
                MetadataDirective='COPY'
            )

            archived_files.append(
                object_key
            )

            print(
                f"Archived: {object_key}"
            )

    print(
        f"Total Archived: {len(archived_files)}"
    )

    return {
        'statusCode': 200,
        'archived_files': archived_files
    }