# -*- coding: utf-8 -*-
"""Lambda_Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grc73lcjd9_Dennh6ijjAazQfB0Xo5G9
"""

import boto3
from datetime import datetime, timedelta

cloudwatch = boto3.client(
    'cloudwatch',
    region_name='us-east-1'
)

sns = boto3.client('sns')

THRESHOLD = 50

TOPIC_ARN = 'arn:aws:sns:ap-south-1:663130434850:AWSBillingAlerts'

def lambda_handler(event, context):

    end_time = datetime.utcnow()
    start_time = end_time - timedelta(days=1)

    response = cloudwatch.get_metric_statistics(
        Namespace='AWS/Billing',
        MetricName='EstimatedCharges',
        Dimensions=[
            {
                'Name': 'Currency',
                'Value': 'USD'
            }
        ],
        StartTime=start_time,
        EndTime=end_time,
        Period=86400,
        Statistics=['Maximum']
    )

    datapoints = response['Datapoints']

    if not datapoints:
        print("No billing data found")
        return

    current_charge = max(
        point['Maximum']
        for point in datapoints
    )

    print(
        f"Current Estimated Charge: ${current_charge}"
    )

    if current_charge > THRESHOLD:

        message = (
            f"AWS Billing Alert!\n\n"
            f"Current Cost: ${current_charge}\n"
            f"Threshold: ${THRESHOLD}"
        )

        sns.publish(
            TopicArn=TOPIC_ARN,
            Subject='AWS Billing Alert',
            Message=message
        )

        print(
            "Billing alert sent."
        )

    else:

        print(
            "Billing below threshold."
        )

    return {
        'statusCode': 200,
        'current_charge': current_charge
    }